<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Map" nsURI="ca.mcgill.ecse459.map" nsPrefix="ca.mcgill.ecse459.map">
  <eClassifiers xsi:type="ecore:EClass" name="Map">
    <eStructuralFeatures xsi:type="ecore:EReference" name="grid" upperBound="-1" eType="#//Grid"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Grid" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Grid"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Grid"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="up" eType="#//Grid"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="down" eType="#//Grid"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Forest" eSuperTypes="#//Grid"/>
  <eClassifiers xsi:type="ecore:EClass" name="City" eSuperTypes="#//Grid"/>
  <eClassifiers xsi:type="ecore:EClass" name="Mountain" eSuperTypes="#//Grid"/>
  <eClassifiers xsi:type="ecore:EClass" name="Lake" eSuperTypes="#//Grid"/>
</ecore:EPackage>
