//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratedClasses
{
    using System;
    using System.Collections.Generic;
    
    public class Grid
    {
        
        private int id;
        
        public Grid Left {
            get;
            set;
        }

        public Grid Right
        {
            get;
            set;
        }

        public Grid Up
        {
            get;
            set;
        }

        public Grid Down
        {
            get;
            set;
        }

        public List<GridType> Types
        {
            get;
            set;
        }

        public Grid(int id)
        {
            this.id = id;
        }
        
        public int Id
        {
            get
            {
                return this.id;
            }
            set
            {
                this.id = value;
            }
        }
    }
}
