//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GeneratedClasses
{
    using System;
    using System.Collections.Generic;


    public abstract class Region
    {
        public int Octaves { get; set; }
        public double Persistence { get; set; }
        public double Lacunarity { get; set; }
        public double MeshHeightMultiplier { get; set; }
        public Region close;
        public List<Region> subregions;

        public Region()
        {
            subregions = new List<Region>();
        }
    }
}